Ajax.Autocompleter.prototype.urlPost="/autocompleter/suggest";Varien.searchForm.prototype.submit=function(a){return this.field.value==this.emptyText||""==this.field.value?(Event.stop(a),!1):keyBoard.first?!0:(Event.stop(a),document.location.href=this.form.action,!1)};Ajax.Autocompleter.prototype.initialize=function(a,b,c,d){this.baseInitialize(a,b,d);this.options.asynchronous=!0;this.options.onComplete=this.onComplete.bind(this);this.options.defaultParams=this.options.parameters||null;this.url=this.urlPost};
Ajax.Autocompleter.prototype.getUpdatedChoices=function(){if(this.oldElementValue!=this.element.value||0==$("search_autocomplete").innerHTML.length){this.startIndicator();var a=encodeURIComponent(this.options.paramName)+"="+encodeURIComponent(this.getToken());this.options.parameters=this.options.callback?this.options.callback(this.element,a):a;this.options.defaultParams&&(this.options.parameters+="&"+this.options.defaultParams);new Ajax.Request(getAutocompleteBaseUrl()+this.url,this.options)}};
Autocompleter.Base.prototype.updateChoices=function(a){keyBoard.first=!0;keyBoard.cats=0;keyBoard.pros=0;if(!this.changed&&this.hasFocus){if(a&&"null"!==a&&"undefined"!==a){a=a.evalJSON();this.update.innerHTML="";if(a.heading_text){var b=(new Element("p",{id:"heading_text_autocomplete"})).update(a.heading_text);this.update.appendChild(b)}if(this.choicesValidator(a.category_results)){var b=(new Element("p",{id:"heading_category_autocomplete"})).update(a.category_head),c=this.createCategoryList(a.category_results);
this.update.appendChild(b);this.update.appendChild(c)}this.choicesValidator(a.product_results)&&(b=(new Element("p",{id:"heading_product_autocomplete"})).update(a.product_head),c=this.createProductList(a.product_results),this.update.appendChild(b),this.update.appendChild(c));!this.choicesValidator(a.category_results)&&!this.choicesValidator(a.product_results)||this.isObjEmpty(a.search_url)||(a=(new Element("a",{id:"search_url_autocomplete",href:a.search_url.url})).update(a.search_url.label),this.update.appendChild(a));
a=$$("#search").first();b=a.cumulativeOffset();b.top=b.top+parseInt(a.getHeight())+3;Prototype.Browser.IE||(b.left-=parseInt(a.getStyle("padding-left"))+3);this.update.setStyle({top:b.top+"px",left:b.left+"px",position:"absolute"});this.update.show()}this.stopIndicator()}};Autocompleter.Base.prototype.choicesValidator=function(a){return a&&null!==a&&void 0!==a&&"undefined"!==a&&""!==a&&a.length?!0:!1};
Autocompleter.Base.prototype.startIndicator=function(){$$("#search").first().setStyle({backgroundImage:'url("http://'+window.location.host+'/skin/frontend/default/default/images/opc-ajax-loader.gif")',backgroundRepeat:"no-repeat",backgroundPosition:"right"})};Autocompleter.Base.prototype.stopIndicator=function(){$$("#search").first().setStyle({backgroundImage:"none"})};
Autocompleter.Base.prototype.createCategoryList=function(a){var b=new Element("ul",{id:"categories_results_autocomplete"});keyBoard.cats=a.length;for(var c=0;c<a.length;c++){var d=(new Element("ol")).update(a[c].label),d=(new Element("li",{"class":"odd search_res"})).update(d),e=(new Element("p",{"class":"hidden_url"})).update(a[c].url);d.appendChild(e);d.setOnClick(a[c].url);b.appendChild(d)}return b};
Autocompleter.Base.prototype.createProductList=function(a){var b=new Element("ul",{id:"products_results_autocomplete"});keyBoard.pros=a.length;for(var c=0;c<a.length;c++){var d=a[c].description,e=(new Element("p")).update((new Element("strong")).update(a[c].name)),g=(new Element("p")).update(d),h=(new Element("p")).update((new Element("strong")).update(a[c].price)),k=new Element("img",{src:a[c].image}),f=new Element("ol"),d=(new Element("p",{"class":"hidden_url"})).update(a[c].url);f.appendChild(k);
f.appendChild(e);f.appendChild(h);f.appendChild(g);e=(new Element("li",{"class":"odd search_res",title:a[c].description})).update(f);e.appendChild(d);e.setOnClick(a[c].url);b.appendChild(e)}return b};Autocompleter.Base.prototype.isObjEmpty=function(a){for(var b in a)if(a.hasOwnProperty(b))return!1;return!0};Element.addMethods({setOnClick:function(a,b){a.onclick=function(a){return function(){window.location.href=a}}(b)}});
String.prototype.trunc=function(a){return this.substr(0,a-1)+(this.length>a?"&hellip;":"")};document.observe("keydown",function(a,b){keyBoard.init(a,b)});var keyBoard=new KeyBoard;
function KeyBoard(){this.pros=this.cats=this.curr=0;this.first=!0;this.init=function(a,b){if(a.findElement("#search")){if(40==a.keyCode){var c=this.curr;this.first||c>=$$(".search_res").length-1?c=0:c++;this.setActiveEl(c)}38==a.keyCode&&(c=this.curr,this.first||0>=c?c=$$(".search_res").length-1:c--,this.setActiveEl(c))}};this.setActiveEl=function(a){this.curr=a;this.first=!1;0<$("search_autocomplete").innerHTML.length&&($("search_autocomplete").show(),$$(".search_res").each(function(a){a.removeClassName("search_autocomplete_li_hover")}),
$$(".search_res")[a]&&($$(".search_res")[a].addClassName("search_autocomplete_li_hover"),$("search_mini_form").setAttribute("action",$$(".search_res")[a].getElementsByClassName("hidden_url")[0].innerHTML),this.scrollCats(a),this.scrollPros(a)))};this.scrollCats=function(a){if(a<this.cats){var b=$("categories_results_autocomplete");4<a&&(b.scrollTop=b.scrollHeight);0>=a&&(b.scrollTop=0)}};this.scrollPros=function(a){if(a>=this.cats){var b=$("products_results_autocomplete");4<a-this.cats&&(b.scrollTop=
b.scrollHeight);0>=a-this.cats&&(b.scrollTop=0)}}};
